import './app.css';
const {invoke}=window.__TAURI__?.core||{};
const call=(cmd,args)=>invoke?invoke(cmd,args):Promise.resolve(cmd==='app_initialized'?true:false);
const nav=['Dashboard','POS','Waiters','Items & Categories','Raw Materials','Expenses','Reports','Settings'];
function money(n){return `ETB ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
async function start(){try{const ready=await call('app_initialized'); ready?login():setup()}catch(e){setup()}}
function setup(){document.querySelector('#app').innerHTML=`<main class="login"><section class="login-box"><h1>NATRA</h1><p>Restaurant Management · First-time setup</p><form id="setup"><label>Full name</label><input id="name" required><label>Username</label><input id="user" minlength="3" required><label>Password</label><input id="pass" type="password" minlength="8" required><label>Confirm password</label><input id="confirm" type="password" minlength="8" required><button class="primary">Create Administrator</button><div id="err" class="error"></div></form></section></main>`;document.querySelector('#setup').onsubmit=async e=>{e.preventDefault();if(pass.value!==confirm.value)return err.textContent='Passwords do not match.';try{await call('create_admin',{username:user.value,password:pass.value,fullName:name.value});login()}catch(x){err.textContent=x}}}
function login(){document.querySelector('#app').innerHTML=`<main class="login"><section class="login-box"><h1>NATRA</h1><p>Restaurant Management</p><form id="login"><label>Username</label><input id="user" required><label>Password</label><input id="pass" type="password" required><button class="primary">Sign in</button><div id="err" class="error"></div></form></section></main>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{if(await call('login',{username:user.value,password:pass.value}))dashboard();else err.textContent='Invalid username or password.'}catch(x){err.textContent=x}}}
async function dashboard(){let s={};try{s=await call('dashboard_summary')}catch{}document.querySelector('#app').innerHTML=`<div class="app"><aside class="sidebar"><div class="logo">NATRA</div><nav class="nav">${nav.map((x,i)=>`<button class="${i?'':'active'}">${x}</button>`).join('')}</nav></aside><main class="main"><header class="topbar"><h1 class="title">Dashboard</h1><span class="status">● Local mode</span></header><section class="cards"><div class="card"><div class="label">Total Sales</div><div class="value">${money(s.sales)}</div></div><div class="card"><div class="label">Ready-made Cost</div><div class="value">${money(s.ready_made_cost)}</div></div><div class="card"><div class="label">Raw Material Cost</div><div class="value">${money(s.raw_material_cost)}</div></div><div class="card"><div class="label">Net Profit</div><div class="value">${money(s.net_profit)}</div></div></section><section class="panel"><h2>Restaurant Management</h2><p>Foundation is ready. POS, waiters, items, raw materials, expenses, reports and optional Turso sync will be implemented as separate modules.</p></section></main></div>`}
start();
